direccion_index:
    path:     /
    defaults: { _controller: "PruebaCrudBundle:Direccion:index" }
    methods:  GET

direccion_show:
    path:     /{id}/show
    defaults: { _controller: "PruebaCrudBundle:Direccion:show" }
    methods:  GET

direccion_new:
    path:     /new
    defaults: { _controller: "PruebaCrudBundle:Direccion:new" }
    methods:  [GET, POST]

direccion_edit:
    path:     /{id}/edit
    defaults: { _controller: "PruebaCrudBundle:Direccion:edit" }
    methods:  [GET, POST]

direccion_delete:
    path:     /{id}/delete
    defaults: { _controller: "PruebaCrudBundle:Direccion:delete" }
    methods:  DELETE
